add: buttons
js-tasks-ru/htmlcss-20230124_aemulatio pull request #4
Opened 2023-02-13 17:48 UTC by Aemulatio

2023-02-13 17:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 10:51 UTC, GSemikozov requested changes

2023-02-14 10:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	padding: 15px 66px;
по макету высота кнопки 48 а не 49 )

2023-02-14 10:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:hover, .button_primary_hover {
классы по типу .button_primary_hover - лишние, мы обрабатываем встроенные состояния по типу :hover, соответственно состояния при котором мы будем вешать класс .button_primary_hover - у нас не будет)

2023-02-14 10:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	background: #4263EB;
pointer-events: none

2023-02-14 10:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:disabled, .button_primary_disabled {
disabled будет общим для всех типов кнопок - .button:disabled

2023-02-14 10:51 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +<button class="button button_alternate">
в разметку также стоит добавить кнопки с атрибутом disabled

2023-02-15 18:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-19 12:40 UTC, GSemikozov approved these changes

2023-02-19 12:40 UTC, merged